def includeme(config):
    config.add_static_view('static', 'static', cache_max_age=3600)
    config.add_route('home', '/')
    config.add_route('campaigns', '/campaigns')
    config.add_route('campaign', '/campaigns/{id}')
    config.add_route('get_top_donation','/donations/top')
    config.add_route('get_campaign_donations','/campaigns/{id}/donations')
    config.add_route('get_token','/token')
    config.add_route('donations', '/donations')
    config.add_route('donation', '/donations/{id}')
    config.add_route('transactions', '/transactions')
    config.add_route('transaction', '/transactions/{id}')
    config.add_route('withdrawals', '/withdrawals')
    config.add_route('withdrawal', '/withdrawals/{id}')
    config.add_route('users', '/users')
    config.add_route('user', '/users/{id}')